services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WechatPayTransferBundle\Repository\:
    resource: '../../Repository/'
    public: true

  WechatPayTransferBundle\Controller\Admin\:
    resource: '../../Controller/Admin/'
    tags: ['controller.service_arguments']

  WechatPayTransferBundle\Controller\Api\:
    resource: '../../Controller/Api/'
    tags: ['controller.service_arguments']

  WechatPayTransferBundle\Command\:
    resource: '../../Command/'

  WechatPayTransferBundle\Service\:
    resource: '../../Service/'
    public: true
